### ISSUE TITLE
Runtime error when using `LabelledGeneric` and `@@`

### ISSUE THREAD

**Issue by alexarchambault** [milessabin/shapeless#310]
Having defined
```scala
trait CustomTag
case class Dummy(i: Int @@ CustomTag)
val lgen = LabelledGeneric[Dummy]
```
the following:
```scala
Console.out println s"${lgen from Record(i=tag[CustomTag](0))}"
```
raises an `AbstractMethodError` at runtime (full example here: https://gist.github.com/alexarchambault/d591ad927984f01f221c)

Curiously, when using scalaz `@@` instead, it seems to work.

**Comment by milessabin** [comment]
I would usually associate `AbstractMethodErrors` with b0rked incremental builds or with REPL interaction. Are you seeing an `AbstractMethodError` when doing a clean build?

**Comment by alexarchambault** [comment]
yup, getting the following with a fresh build:
```scala
error] (run-main-0) java.lang.AbstractMethodError: Dummy$fresh$macro$2$1.from(Ljava/lang/Object;)Ljava/lang/Object;
java.lang.AbstractMethodError: Dummy$fresh$macro$2$1.from(Ljava/lang/Object;)Ljava/lang/Object;
	at Dummy$.delayedEndpoint$Dummy$1(Dummy.scala:8)
	at Dummy$delayedInit$body.apply(Dummy.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Dummy$.main(Dummy.scala:6)
	at Dummy.main(Dummy.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 0 s, completed 13 janv. 2015 00:25:53
```

**Comment by alexarchambault** [comment]
Same thing without the `DelayedInit`:
```scala
[error] (run-main-0) java.lang.AbstractMethodError: Dummy$fresh$macro$2$1.from(Ljava/lang/Object;)Ljava/lang/Object;
java.lang.AbstractMethodError: Dummy$fresh$macro$2$1.from(Ljava/lang/Object;)Ljava/lang/Object;
	at Dummy$.main(Dummy.scala:9)
	at Dummy.main(Dummy.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 8 s, completed 13 janv. 2015 00:29:53
```

`Dummy.scala`
```scala
import shapeless._, tag._, record._

trait CustomTag
case class Dummy(i: Int @@ CustomTag)

object Dummy {
  def main(args: Array[String]): Unit = {
    val lgen = LabelledGeneric[Dummy]
    Console.out println s"${lgen from Record(i=tag[CustomTag](0))}"
  }
}
```
