### ISSUE TITLE
cachedImplicit does not shadow lazy val definitions

### ISSUE THREAD

**Issue by Taig** [milessabin/shapeless#553]
Defining a `cachedImplicit` with a `lazy val` results in a StackOverflowError since shapeless 2.3.0. On a side note it is also no longer possible to omit the type argument of `cachedImplicit` when used lazily.

```scala
import shapeless._

trait MyType[T] { def foo: T }

object MyType {
    implicit val myTypeString: MyType[String] = new MyType[String] {
        override def foo: String = "bar"
    }
}

object Val extends App {
    implicit val ci: MyType[String] = cachedImplicit

    println( ci.foo )
}

object LazyVal extends App {
    implicit lazy val ci: MyType[String] = cachedImplicit[MyType[String]] // Type inference no longer possible

    println( ci.foo )
}

object Def extends App {
    implicit def ci: MyType[String] = cachedImplicit[MyType[String]] // Type inference no longer possible

    println( ci.foo )
}
```

```
> run
[info] Updating {file:/Users/Taig/Desktop/test/}test...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 1 Scala source to ./test/target/scala-2.11/classes...
[warn]./test/src/main/scala/Test.scala:24: method ci in object Def does nothing other than call itself recursively
[warn]     implicit def ci: MyType[String] = cachedImplicit[MyType[String]] // Type inference no longer possible
[warn]                                                     ^
[warn] one warning found
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] Def
 [2] LazyVal
 [3] Val
number: 3

[info] Running Val 
bar
[success] Total time: 6 s, completed 28.02.2016 00:42:53
> run
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] Def
 [2] LazyVal
 [3] Val
number: 2

[info] Running LazyVal 
[error] (run-main-1) java.lang.StackOverflowError
java.lang.StackOverflowError
	at LazyVal$.ci(Test.scala:18)
	at LazyVal$.ci$lzycompute(Test.scala:18)
	at LazyVal$.ci(Test.scala:18)
	at LazyVal$.ci$lzycompute(Test.scala:18)
	...
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 2 s, completed 28.02.2016 00:42:57
> run
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] Def
 [2] LazyVal
 [3] Val
number: 1

[info] Running Def
```

**Comment by milessabin** [comment]
Thanks for that. Are you able to work around this for now by dropping the `lazy` qualifier?

**Comment by Taig** [comment]
It's not a blocker for me since I can move the cache definitions into the companions now. I wasn't planning to do that now, but plans just changed.

**Comment by milessabin** [comment]
One observation ... `cachedImplicit` should always be used with a val (lazy or otherwise) rather than a def ... I'll see if I can catch and reject that case.
