### ISSUE TITLE
NoSuchMethodError when using enum example with anonymous abstract class (non-lazy) vals

### ISSUE THREAD

**Issue by ramirez7** [milessabin/shapeless#560]
Here's the code, which is based on the [enum example](https://github.com/milessabin/shapeless/blob/2a1c0a98fcd4ab9b2cb14d441f77015591f0a367/examples/src/main/scala/shapeless/examples/enum.scala):

```scala
object Test {
  sealed abstract class Enum(val x: Int, val y: Boolean) {
    override def toString: String = s"Enum($x $y)"
  }
  val One = new Enum(1, true){}
  val Two = new Enum(2, false){}
  val values: Set[Enum] = ShapelessEnum.Values[Enum]
  def fromInt(n: Int): Option[Enum] = values.find(_.x == n)
  def fromBool(b: Boolean): Option[Enum] = values.find(_.y == b)

  import shapeless._
  // Taken from (+ example usage):
  // https://github.com/milessabin/shapeless/blob/2a1c0a98fcd4ab9b2cb14d441f77015591f0a367/examples/src/main/scala/shapeless/examples/enum.scala
  object ShapelessEnum {
    object Values {
      def apply[T](implicit v: MkValues[T]): Set[T] = v.values.toSet

      trait MkValues[T] {
        def values: List[T]
      }

      object MkValues {
        implicit def values[T, Repr <: Coproduct]
          (implicit gen: Generic.Aux[T, Repr], v: Aux[T, Repr]): MkValues[T] =
          new MkValues[T] { def values = v.values }

        trait Aux[T, Repr] {
          def values: List[T]
        }

        object Aux {
          implicit def cnilAux[A]: Aux[A, CNil] =
            new Aux[A, CNil] { def values = Nil }

          implicit def cconsAux[T, L <: T, R <: Coproduct]
            (implicit l: Witness.Aux[L], r: Aux[T, R]): Aux[T, L :+: R] =
            new Aux[T, L :+: R] { def values = l.value :: r.values }
        }
      }
    }
  }
}
```

Here is what happens when I try to reference the vals in the REPL:

```scala
scala> Test.One
java.lang.NoSuchMethodError: Test$.One()LTest$Enum;
  ... 43 elided

scala> Test.Two
java.lang.NoSuchMethodError: Test$.Two()LTest$Enum;
  ... 43 elided
```

Interestingly, the vals **do** seem to exist. If I use `fromInt`, I can successfully get a reference to them:

```scala
scala> Test.fromInt(1)
res2: Option[Test.Enum] = Some(Enum(1 true))

scala> Test.fromInt(2)
res3: Option[Test.Enum] = Some(Enum(2 false))
```

It's just the actual val that doesn't work. If I make `One` and `Two` lazy vals, I can reference them without a `NoSuchMethodError`. If I leave `One` and `Two` as vals and make `values` a lazy val or def, I still get the error.

If I get rid of `values`, it works as well. This makes me think it has something to do with the implicits/macros that `values` calls and their interaction with the two vals.

I got this to happen in shapeless 2.2.5 and 2.3.0. It isn't just present in the REPL either: It first occurred when I ran unit tests for the actual code the small example is based on. It also happens when I reference the val in main:

```scala
object Main extends App {
  println("BEGIN")
  println(Test.One)
  println("END")
}
```

The result of `sbt run`:
```scala
[info] Running Main 
BEGIN
[error] (run-main-5) java.lang.NoSuchMethodError: Test$.One()LTest$Enum;
java.lang.NoSuchMethodError: Test$.One()LTest$Enum;
	at Main$.delayedEndpoint$Main$1(Main.scala:3)
	at Main$delayedInit$body.apply(Main.scala:1)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Main$.main(Main.scala:1)
	at Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 1 s, completed Mar 10, 2016 4:48:54 PM
```

For now, I'm just using lazy vals everywhere and it gets the job done.

**Comment by milessabin** [comment]
I can reproduce this on the REPL, but not via a compiled main. This is with Scala 2.11.8.

**Comment by milessabin** [comment]
I can also reproduce this on the REPL with 2.12.0-M3.
