### ISSUE TITLE
Serialisation of type inequality traits fails

### ISSUE THREAD

**Issue by AndreasKostler** [milessabin/shapeless#622]
The type inequality traits `=:!=` and `<:!<` do not extend `Serializable` and will therefore throw and exception when used in a context where serialisation is required:

```scala
val oos = new ObjectOutputStream(System.out)
oos.writeObject(new =:!=[Int, Doube]{}) /// BOOM!
```

**Comment by milessabin** [comment]
I think this is desirable, or at least not a bad thing: the proof embodied in the value wouldn't survive being serialized and deserialized because of erasure.

**Comment by AndreasKostler** [comment]
Oh...Do you have any suggestion on how to use this in a context where serialisation is required? I.e. is there a way to provide that proof?

**Comment by milessabin** [comment]
Could you give me an example of how you would want to use this before and after serialization?

**Comment by AndreasKostler** [comment]
This is what happens...
```scala
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
    at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:304)
    at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:294)
    at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
    at org.apache.spark.SparkContext.clean(SparkContext.scala:2021)
    at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:314)
    at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:313)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
    at org.apache.spark.rdd.RDD.map(RDD.scala:313)
    at commbank.grimlock.spark.ReducibleMatrix$class.melt(Matrix.scala:749)
    at commbank.grimlock.spark.Matrix5D.melt(Matrix.scala:1438)
    at commbank.grimlock.spark.examples.Conditional$.main(Conditional.scala:65)
    at commbank.grimlock.spark.examples.Conditional.main(Conditional.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.NotSerializableException: shapeless.package$$anon$2
Serialization stack:
    - object not serializable (class: shapeless.package$$anon$2, value: shapeless.package$$anon$2@166b21ea)
    - field (class: commbank.grimlock.spark.ReducibleMatrix$$anonfun$melt$1, name: ev3$19, type: interface shapeless.package$$eq$colon$bang$eq)
    - object (class commbank.grimlock.spark.ReducibleMatrix$$anonfun$melt$1, <function1>)
    at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
    at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
    at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:84)
    at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:301)
    ... 22 more

examples/src/.../spark/Conditional.scala line 65

  val heg = data
    .reshape(_2, "hair", cast)
    .reshape(_2, "eye", cast)
    .reshape(_2, "gender", cast)
    .melt(_2, _1, Value.concatenate("."))  // <- this line
    .squash(_1, PreservingMaxPosition())

core/src/.../spark/Matrix.scal line 749

  def melt[
    D <: Nat : ToInt,
    I <: Nat : ToInt
  ](
    dim: D,
    into: I,
    merge: (Value, Value) => Value
  )(implicit
    ev1: LTEq[D, P],
    ev2: LTEq[I, P],
    ev3: D =:!= I, // This is the culprit...
    ev4: Diff.Aux[P, _1, L]
  ): U[Cell[L]] = data.map { case Cell(p, c) => Cell(p.melt(dim, into, merge), c) }  // <- this line
```

**Comment by milessabin** [comment]
In this case at least it looks like it doesn't matter that the proof could be forged across a serialization boundary. There's nothing particularly palatable that you could do to work around this, so you've persuaded me ... I'll merge :-)
